var Data = [{'GMT': '-7',
   'airportId': 41,
   'codeIataAirport': 'ABQ',
   'codeIataCity': 'ABQ',
   'codeIcaoAirport': 'KABQ',
   'codeIso2Country': 'US',
   'geonameId': '5454724',
   'latitudeAirport': 35.049625,
   'longitudeAirport': -106.617195,
   'nameAirport': 'Albuquerque International',
   'nameCountry': 'United States',
   'phone': '505-244-7700',
   'timezone': 'America/Denver'},
 {'GMT': '-5',
   'airportId': 411,
   'codeIataAirport': 'ATL',
   'codeIataCity': 'ATL',
   'codeIcaoAirport': 'KATL',
   'codeIso2Country': 'US',
   'geonameId': '4180439',
   'latitudeAirport': 33.640068,
   'longitudeAirport': -84.44403,
   'nameAirport': 'Hartsfield-jackson Atlanta International',
   'nameCountry': 'United States',
   'phone': '800-897-1910',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 1043,
   'codeIataAirport': 'BWI',
   'codeIataCity': 'BWI',
   'codeIcaoAirport': 'KBWI',
   'codeIso2Country': 'US',
   'geonameId': '4347822',
   'latitudeAirport': 39.179527,
   'longitudeAirport': -76.66894,
   'nameAirport': 'Baltimore/Washington International Thurgood Marshall',
   'nameCountry': 'United States',
   'phone': '410-859-7111',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 876,
   'codeIataAirport': 'BOS',
   'codeIataCity': 'BOS',
   'codeIcaoAirport': 'KBOS',
   'codeIso2Country': 'US',
   'geonameId': '4937646',
   'latitudeAirport': 42.36646,
   'longitudeAirport': -71.02018,
   'nameAirport': 'Logan International',
   'nameCountry': 'United States',
   'phone': '1-800-23-LOGAN(56426)',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 1586,
   'codeIataAirport': 'CUN',
   'codeIataCity': 'CUN',
   'codeIcaoAirport': 'MMUN',
   'codeIso2Country': 'MX',
   'geonameId': '6299880',
   'latitudeAirport': 21.040457,
   'longitudeAirport': -86.874435,
   'nameAirport': 'Cancún International',
   'nameCountry': 'Mexico',
   'phone': '(998) 848-720',
   'timezone': 'America/Cancun'},
 {'GMT': '-5',
   'airportId': 1388,
   'codeIataAirport': 'CLT',
   'codeIataCity': 'CLT',
   'codeIcaoAirport': 'KCLT',
   'codeIso2Country': 'US',
   'geonameId': '4460310',
   'latitudeAirport': 35.219166,
   'longitudeAirport': -80.93584,
   'nameAirport': 'Charlotte Douglas',
   'nameCountry': 'United States',
   'phone': '704-359-4000',
   'timezone': 'America/New_York'},
 {'GMT': '-6',
   'airportId': 5818,
   'codeIataAirport': 'ORD',
   'codeIataCity': 'CHI',
   'codeIcaoAirport': 'KORD',
   'codeIso2Country': 'US',
   'geonameId': '4887479',
   'latitudeAirport': 41.976913,
   'longitudeAirport': -87.90488,
   'nameAirport': "Chicago O'hare International",
   'nameCountry': 'United States',
   'phone': '773-686-2200',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 4741,
   'codeIataAirport': 'MDW',
   'codeIataCity': 'CHI',
   'codeIcaoAirport': 'KMDW',
   'codeIso2Country': 'US',
   'geonameId': '4887472',
   'latitudeAirport': 41.788136,
   'longitudeAirport': -87.74087,
   'nameAirport': 'Midway',
   'nameCountry': 'United States',
   'phone': '773-838-9111',
   'timezone': 'America/Chicago'},
 {'GMT': '-7',
   'airportId': 1464,
   'codeIataAirport': 'COS',
   'codeIataCity': 'COS',
   'codeIcaoAirport': 'KCOS',
   'codeIso2Country': 'US',
   'geonameId': '5417598',
   'latitudeAirport': 38.79713,
   'longitudeAirport': -104.70056,
   'nameAirport': 'Colorado Springs',
   'nameCountry': 'United States',
   'phone': '',
   'timezone': 'America/Denver'},
 {'GMT': '-6',
   'airportId': 1692,
   'codeIataAirport': 'DAL',
   'codeIataCity': 'DFW',
   'codeIcaoAirport': 'KDAL',
   'codeIso2Country': 'US',
   'geonameId': '4684922',
   'latitudeAirport': 32.84391,
   'longitudeAirport': -96.85,
   'nameAirport': 'Love Field',
   'nameCountry': 'United States',
   'phone': '214-670-6080',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 1756,
   'codeIataAirport': 'DFW',
   'codeIataCity': 'DFW',
   'codeIcaoAirport': 'KDFW',
   'codeIso2Country': 'US',
   'geonameId': '4684943',
   'latitudeAirport': 32.89746,
   'longitudeAirport': -97.036125,
   'nameAirport': 'Dallas/Fort Worth International',
   'nameCountry': 'United States',
   'phone': '972-973-8888',
   'timezone': 'America/Chicago'},
 {'GMT': '-7',
   'airportId': 1746,
   'codeIataAirport': 'DEN',
   'codeIataCity': 'DEN',
   'codeIcaoAirport': 'KDEN',
   'codeIso2Country': 'US',
   'geonameId': '5419401',
   'latitudeAirport': 39.84939,
   'longitudeAirport': -104.672844,
   'nameAirport': 'Denver International',
   'nameCountry': 'United States',
   'phone': '303-342-2000',
   'timezone': 'America/Denver'},
 {'GMT': '-5',
   'airportId': 1936,
   'codeIataAirport': 'DTW',
   'codeIataCity': 'DTT',
   'codeIcaoAirport': 'KDTW',
   'codeIso2Country': 'US',
   'geonameId': '4990742',
   'latitudeAirport': 42.20781,
   'longitudeAirport': -83.35605,
   'nameAirport': 'Detroit Metropolitan Wayne County',
   'nameCountry': 'United States',
   'phone': '734-247-7678',
   'timezone': 'America/Detroit'},
 {'GMT': '-7',
   'airportId': 2094,
   'codeIataAirport': 'ELP',
   'codeIataCity': 'ELP',
   'codeIcaoAirport': 'KELP',
   'codeIso2Country': 'US',
   'geonameId': '5521012',
   'latitudeAirport': 31.798948,
   'longitudeAirport': -106.396,
   'nameAirport': 'El Paso International Airport',
   'nameCountry': 'United States',
   'phone': '915-780-4749',
   'timezone': 'America/Denver'},
 {'GMT': '-6',
   'airportId': 2538,
   'codeIataAirport': 'GDL',
   'codeIataCity': 'GDL',
   'codeIcaoAirport': 'MMGL',
   'codeIso2Country': 'MX',
   'geonameId': '4011789',
   'latitudeAirport': 20.525198,
   'longitudeAirport': -103.29921,
   'nameAirport': 'Don Miguel Hidalgo y Costilla International',
   'nameCountry': 'Mexico',
   'phone': '',
   'timezone': 'America/Mexico_City'},
 {'GMT': '-6',
   'airportId': 3161,
   'codeIataAirport': 'IAH',
   'codeIataCity': 'HOU',
   'codeIcaoAirport': 'KIAH',
   'codeIso2Country': 'US',
   'geonameId': '4693268',
   'latitudeAirport': 29.983334,
   'longitudeAirport': -95.34,
   'nameAirport': 'George Bush Intercontinental',
   'nameCountry': 'United States',
   'phone': '281-230-3100',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 3039,
   'codeIataAirport': 'HOU',
   'codeIataCity': 'HOU',
   'codeIcaoAirport': 'KHOU',
   'codeIso2Country': 'US',
   'geonameId': '4741989',
   'latitudeAirport': 29.654512,
   'longitudeAirport': -95.277016,
   'nameAirport': 'William P Hobby',
   'nameCountry': 'United States',
   'phone': '281-233-3000',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 4701,
   'codeIataAirport': 'MCI',
   'codeIataCity': 'MKC',
   'codeIcaoAirport': 'KMCI',
   'codeIso2Country': 'US',
   'geonameId': '4393219',
   'latitudeAirport': 39.293808,
   'longitudeAirport': -94.719925,
   'nameAirport': 'Kansas City International Airport',
   'nameCountry': 'United States',
   'phone': '816-243-5237',
   'timezone': 'America/Chicago'},
 {'GMT': '-8',
   'airportId': 4184,
   'codeIataAirport': 'LAS',
   'codeIataCity': 'LAS',
   'codeIcaoAirport': 'KLAS',
   'codeIso2Country': 'US',
   'geonameId': '5507974',
   'latitudeAirport': 36.086945,
   'longitudeAirport': -115.1486,
   'nameAirport': 'Mc Carran International',
   'nameCountry': 'United States',
   'phone': '702-261-5211',
   'timezone': 'America/Los_Angeles'},
 {'GMT': '-6',
   'airportId': 761,
   'codeIataAirport': 'BJX',
   'codeIataCity': 'BJX',
   'codeIcaoAirport': 'MMLO',
   'codeIso2Country': 'MX',
   'geonameId': '6299851',
   'latitudeAirport': 20.985699,
   'longitudeAirport': -101.479,
   'nameAirport': 'Del Bajío International',
   'nameCountry': 'Mexico',
   'phone': '',
   'timezone': 'America/Mexico_City'},
 {'GMT': '-8',
   'airportId': 4189,
   'codeIataAirport': 'LAX',
   'codeIataCity': 'LAX',
   'codeIcaoAirport': 'KLAX',
   'codeIso2Country': 'US',
   'geonameId': '5368418',
   'latitudeAirport': 33.943398,
   'longitudeAirport': -118.40828,
   'nameAirport': 'Los Angeles International',
   'nameCountry': 'United States',
   'phone': '310-646-5252',
   'timezone': 'America/Los_Angeles'},
 {'GMT': '-6',
   'airportId': 4768,
   'codeIataAirport': 'MEX',
   'codeIataCity': 'MEX',
   'codeIcaoAirport': 'MMMX',
   'codeIso2Country': 'MX',
   'geonameId': '6299859',
   'latitudeAirport': 19.435278,
   'longitudeAirport': -99.07278,
   'nameAirport': 'Internacional Benito Juarez',
   'nameCountry': 'Mexico',
   'phone': '2482-2424',
   'timezone': 'America/Mexico_City'},
 {'GMT': '-5',
   'airportId': 4845,
   'codeIataAirport': 'MIA',
   'codeIataCity': 'MIA',
   'codeIcaoAirport': 'KMIA',
   'codeIso2Country': 'US',
   'geonameId': '4164181',
   'latitudeAirport': 25.796,
   'longitudeAirport': -80.27824,
   'nameAirport': 'Miami International Airport',
   'nameCountry': 'United States',
   'phone': '305-876-7000',
   'timezone': 'America/New_York'},
 {'GMT': '-6',
   'airportId': 5106,
   'codeIataAirport': 'MSP',
   'codeIataCity': 'MSP',
   'codeIcaoAirport': 'KMSP',
   'codeIso2Country': 'US',
   'geonameId': '5037658',
   'latitudeAirport': 44.883015,
   'longitudeAirport': -93.21092,
   'nameAirport': 'Minneapolis - St. Paul International',
   'nameCountry': 'United States',
   'phone': '612-726-5555',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 5141,
   'codeIataAirport': 'MTY',
   'codeIataCity': 'MTY',
   'codeIcaoAirport': 'MMMY',
   'codeIso2Country': 'MX',
   'geonameId': '6299860',
   'latitudeAirport': 25.77657,
   'longitudeAirport': -100.114395,
   'nameAirport': 'Gen Mariano Escobedo',
   'nameCountry': 'Mexico',
   'phone': '',
   'timezone': 'America/Monterrey'},
 {'GMT': '-6',
   'airportId': 838,
   'codeIataAirport': 'BNA',
   'codeIataCity': 'BNA',
   'codeIcaoAirport': 'KBNA',
   'codeIso2Country': 'US',
   'geonameId': '4644589',
   'latitudeAirport': 36.13174,
   'longitudeAirport': -86.668945,
   'nameAirport': 'Nashville International',
   'nameCountry': 'United States',
   'phone': '615-275-1675',
   'timezone': 'America/Chicago'},
 {'GMT': '-6',
   'airportId': 5115,
   'codeIataAirport': 'MSY',
   'codeIataCity': 'MSY',
   'codeIcaoAirport': 'KMSY',
   'codeIso2Country': 'US',
   'geonameId': '4335061',
   'latitudeAirport': 29.984564,
   'longitudeAirport': -90.25639,
   'nameAirport': 'Louis Armstrong New Orléans International Airport',
   'nameCountry': 'United States',
   'phone': '504-303-7500',
   'timezone': 'America/Chicago'},
 {'GMT': '-5',
   'airportId': 3498,
   'codeIataAirport': 'JFK',
   'codeIataCity': 'NYC',
   'codeIcaoAirport': 'KJFK',
   'codeIso2Country': 'US',
   'geonameId': '5122732',
   'latitudeAirport': 40.642334,
   'longitudeAirport': -73.78817,
   'nameAirport': 'John F Kennedy International',
   'nameCountry': 'United States',
   'phone': '718-244-4444',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 2232,
   'codeIataAirport': 'EWR',
   'codeIataCity': 'NYC',
   'codeIcaoAirport': 'KEWR',
   'codeIso2Country': 'US',
   'geonameId': '5101809',
   'latitudeAirport': 40.68907,
   'longitudeAirport': -74.17876,
   'nameAirport': 'Newark Liberty International',
   'nameCountry': 'United States',
   'phone': '973-961- 6000',
   'timezone': 'America/New_York'},
 {'GMT': '-6',
   'airportId': 5722,
   'codeIataAirport': 'OKC',
   'codeIataCity': 'OKC',
   'codeIcaoAirport': 'KOKC',
   'codeIso2Country': 'US',
   'geonameId': '4555726',
   'latitudeAirport': 35.39563,
   'longitudeAirport': -97.59609,
   'nameAirport': 'Will Rogers World Airport',
   'nameCountry': 'United States',
   'phone': '405-316-3271',
   'timezone': 'America/Chicago'},
 {'GMT': '-5',
   'airportId': 4707,
   'codeIataAirport': 'MCO',
   'codeIataCity': 'ORL',
   'codeIcaoAirport': 'KMCO',
   'codeIso2Country': 'US',
   'geonameId': '4167162',
   'latitudeAirport': 28.432177,
   'longitudeAirport': -81.308304,
   'nameAirport': 'Orlando International',
   'nameCountry': 'United States',
   'phone': '407-825-2001',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 6091,
   'codeIataAirport': 'PHL',
   'codeIataCity': 'PHL',
   'codeIcaoAirport': 'KPHL',
   'codeIso2Country': 'US',
   'geonameId': '4560349',
   'latitudeAirport': 39.87641,
   'longitudeAirport': -75.2433,
   'nameAirport': 'Philadelphia International',
   'nameCountry': 'United States',
   'phone': '215-937-6937',
   'timezone': 'America/New_York'},
 {'GMT': '-7',
   'airportId': 6100,
   'codeIataAirport': 'PHX',
   'codeIataCity': 'PHX',
   'codeIcaoAirport': 'KPHX',
   'codeIso2Country': 'US',
   'geonameId': '5308700',
   'latitudeAirport': 33.435036,
   'longitudeAirport': -112.00016,
   'nameAirport': 'Sky Harbor International',
   'nameCountry': 'United States',
   'phone': '602-273-3300',
   'timezone': 'America/Phoenix'},
 {'GMT': '-7',
   'airportId': 7174,
   'codeIataAirport': 'SLC',
   'codeIataCity': 'SLC',
   'codeIcaoAirport': 'KSLC',
   'codeIso2Country': 'US',
   'geonameId': '5780999',
   'latitudeAirport': 40.785645,
   'longitudeAirport': -111.980675,
   'nameAirport': 'Salt Lake City International',
   'nameCountry': 'United States',
   'phone': '801-575-2400',
   'timezone': 'America/Denver'},
 {'GMT': '-8',
   'airportId': 6920,
   'codeIataAirport': 'SAN',
   'codeIataCity': 'SAN',
   'codeIcaoAirport': 'KSAN',
   'codeIso2Country': 'US',
   'geonameId': '5391847',
   'latitudeAirport': 32.731937,
   'longitudeAirport': -117.19731,
   'nameAirport': 'San Diego International Airport',
   'nameCountry': 'United States',
   'phone': '619-400-2404',
   'timezone': 'America/Los_Angeles'},
 {'GMT': '-8',
   'airportId': 7038,
   'codeIataAirport': 'SFO',
   'codeIataCity': 'SFO',
   'codeIcaoAirport': 'KSFO',
   'codeIso2Country': 'US',
   'geonameId': '5391989',
   'latitudeAirport': 37.615215,
   'longitudeAirport': -122.38988,
   'nameAirport': 'San Francisco International',
   'nameCountry': 'United States',
   'phone': '650-821-8211',
   'timezone': 'America/Los_Angeles'},
 {'GMT': '-8',
   'airportId': 7004,
   'codeIataAirport': 'SEA',
   'codeIataCity': 'SEA',
   'codeIcaoAirport': 'KSEA',
   'codeIso2Country': 'US',
   'geonameId': '5809876',
   'latitudeAirport': 47.44384,
   'longitudeAirport': -122.301735,
   'nameAirport': 'Seattle-Tacoma International',
   'nameCountry': 'United States',
   'phone': '206-787-5388',
   'timezone': 'America/Los_Angeles'},
 {'GMT': '-6',
   'airportId': 7378,
   'codeIataAirport': 'STL',
   'codeIataCity': 'STL',
   'codeIcaoAirport': 'KSTL',
   'codeIso2Country': 'US',
   'geonameId': '4394516',
   'latitudeAirport': 38.74228,
   'longitudeAirport': -90.36587,
   'nameAirport': 'Lambert-St. Louis International',
   'nameCountry': 'United States',
   'phone': '314-426-8000',
   'timezone': 'America/Chicago'},
 {'GMT': '-5',
   'airportId': 7865,
   'codeIataAirport': 'TPA',
   'codeIataCity': 'TPA',
   'codeIcaoAirport': 'KTPA',
   'codeIso2Country': 'US',
   'geonameId': '4174772',
   'latitudeAirport': 27.97987,
   'longitudeAirport': -82.535416,
   'nameAirport': 'Tampa International',
   'nameCountry': 'United States',
   'phone': '813-870-3770',
   'timezone': 'America/New_York'},
 {'GMT': '-5',
   'airportId': 3159,
   'codeIataAirport': 'IAD',
   'codeIataCity': 'WAS',
   'codeIcaoAirport': 'KIAD',
   'codeIso2Country': 'US',
   'geonameId': '4792325',
   'latitudeAirport': 38.95315,
   'longitudeAirport': -77.44774,
   'nameAirport': 'Washington Dulles International',
   'nameCountry': 'United States',
   'phone': '703-572-2700',
   'timezone': 'America/New_York'}];



// Create a map object.
var myMap = L.map("map", {
  center: [37.09, -95.71],
  zoom: 5
});

// Add a tile layer.
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(myMap);



// Looping through the airport Array
for (var i = 0; i < Data.length; i++) {
  var airport =  Data[i];
  L.marker([airport.latitudeAirport, airport.longitudeAirport])
    .bindPopup(`<h1>${airport.nameAirport}</h1> <hr> <h3>Airport Code: ${airport.codeIataAirport}</h3>`)
    .addTo(myMap);
}
